#############################################################################
# Makefile for building: cvMat2Qimge
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  cvMat2Qimge.pro
# Template: app
# Command: /usr/local/Qt5.7.0/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile cvMat2Qimge.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /usr/local/include/opencv2 -I/usr/local/Qt5.7.0/5.7/gcc_64/include -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore -I. -I. -I/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/local/Qt5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cvMat2Qimge1.0.0
DISTDIR = /home/gcnan604/devdata/opencvExample/cvMat2Qimge/.tmp/cvMat2Qimge1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgcodecs.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_shape.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_videoio.so /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -L/usr/local/Qt5.7.0/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		cvmat2qimage.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		cvmat2qimage.o \
		moc_widget.o
DIST          = /usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		cvMat2Qimge.pro widget.h \
		cvmat2qimage.h main.cpp \
		widget.cpp \
		cvmat2qimage.cpp
QMAKE_TARGET  = cvMat2Qimge
DESTDIR       = 
TARGET        = cvMat2Qimge


first: all
####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cvMat2Qimge.pro /usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf /usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		cvMat2Qimge.pro \
		/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl \
		/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl \
		/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile cvMat2Qimge.pro
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
cvMat2Qimge.pro:
/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl:
/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl:
/usr/local/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile cvMat2Qimge.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents widget.h cvmat2qimage.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp cvmat2qimage.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: /usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QWidget \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		widget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/bin/moc
	/usr/local/Qt5.7.0/5.7/gcc_64/bin/moc $(DEFINES) -I/usr/local/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++ -I/home/gcnan604/devdata/opencvExample/cvMat2Qimge -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/usr/local/Qt5.7.0/5.7/gcc_64/include -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui -I/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include widget.h -o moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/usr/local/Qt5.7.0/5.7/gcc_64/bin/uic
	/usr/local/Qt5.7.0/5.7/gcc_64/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QWidget \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QApplication \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qguiapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QWidget \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		ui_widget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/QVariant \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QAction \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qaction.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QApplication \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qguiapplication.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qinputmethod.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QButtonGroup \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qbuttongroup.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QHeaderView \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qheaderview.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qframe.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qvalidator.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qregularexpression.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qslider.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qstyle.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qtabbar.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qrubberband.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/QPushButton \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qpushbutton.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qabstractbutton.h \
		cvmat2qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

cvmat2qimage.o: cvmat2qimage.cpp cvmat2qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/QImage \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/QDebug \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvmat2qimage.o cvmat2qimage.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

